/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _generics_collections;

import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.HashMap;
import java.util.Queue;
import java.util.LinkedList;

public class App {

    public interface IMeasurable {
        double getWeight();
    }

    private static record Pokemon(String name, String type, int level) {
    };

    private static class Finger implements Comparable<Finger> {
        private int length;

        Finger(int length) {
            this.length = length;
        }

        public int getLength() {
            return length;
        }

        @Override
        public int compareTo(Finger finger) {
            return this.length > finger.getLength() ? 1 : 0;
        }
    }

    private class Bag<T> {
        private T content;

        public Bag(T content) {
            this.content = content;
        }

        public T getContent() {
            return content;
        }

        public void setContent(T content) {
            this.content = content;
        }

    }

    private class MeasuredBag<T extends IMeasurable> {
        private T content;

        MeasuredBag(T content) {
            this.content = content;
        }

        public T getContent() {
            return content;
        }

        public void setContent(T content) {
            this.content = content;
        }

        public double getContentWeight() {
            return content.getWeight();
        }

    }

    public static void main(String[] args) {
        List<Pokemon> myPokemon = new ArrayList<Pokemon>();

        myPokemon.add(new Pokemon("Thor", "Electric", 3));
        myPokemon.add(new Pokemon("Luna", "Water", 3));

        List<String> passPhrases = new ArrayList<String>();

        passPhrases.add("OOGA BOOGA");
        passPhrases.add("ABRACADABRA");

        Set<String> emailAddresses = new HashSet<>();
        emailAddresses.add("sarahmilou@amsterdam.com");
        emailAddresses.add("tjed@amsterdam.com");
        emailAddresses.add("fahya@amsterdam.com");

        Map<String, Integer> inventory = new HashMap<String, Integer>();

        inventory.put("Red Pot", 5);
        inventory.put("Blue Pot", 10);
        inventory.put("Yellow Pot", 22);

        int countYellowPot = inventory.get("Yellow Pot");
        inventory.put("Yellow Put", inventory.get("Yellow Pot") + 1);

        Queue<String> myQueue = new LinkedList<>();
        myQueue.add("TEST 1");
        myQueue.add("TEST 2");

        Print("Using non mutating get");
        Print(myQueue.peek());
        String myTest = myQueue.element();
        Print(myQueue.peek());

        Print("Using mutating get");
        Print(myQueue.peek());
        String dummy = myQueue.poll();
        Print(myQueue.peek());
    }

    public static void Print(Object obj) {
        System.out.println(obj);
    }
}
