/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _exceptions;

import java.io.FileReader;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        System.out.println("Working Directory = " + System.getProperty("user.dir"));

        String existingFileName = "input";
        String missingFileName = "missing";

        FileReader reader = null;

        try {
            int character;

            reader = new FileReader(existingFileName);
            while ((character = reader.read()) != -1) {
                System.out.print((char) character);
            }
            reader.close();


            try (MyResource myRes = new App.MyResource()) {
                myRes.DoSomething();
            }

//            reader = new FileReader(missingFileName);
//            while ((character = reader.read()) != -1) {
//                System.out.print((char) character);
//            }

        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            System.out.println("FINAL BLOCK");
            reader.close();
        }
    }

    static class MyResource implements AutoCloseable {
        public void DoSomething() {
            System.out.println("MyResource is doing something");
        }

        @Override
        public void close() {
            System.out.println("Closing MyResource!");
        }
    }
}
