/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _methods;

import java.util.Scanner;

public class App {

    static Scanner SCANNER = new Scanner(System.in);

    public static void main(String[] args) {
        SimpleMethod();
        RunMyNumber();

        int mySum = MyVarArgsSum(1, 2, 3, 4, 5);
        Print(mySum);

        // passing in arr for varargs
        int[] myNums = { 1, 2, 3, 4, 5 };
        mySum = MyVarArgsSum(myNums);

        SCANNER.close();
    }

    public static int MyVarArgsSum(int... args) {
        int sum = 0;

        for (int i : args) {
            sum += i;
        }

        return sum;
    }

    public static void RunMyNumber() {
        int myNum = GiveMeANumber();

        while (myNum < 1 || myNum > 10) {
            myNum = GiveMeANumber();
        }
    }

    public static int GiveMeANumber() {
        Print("Give me a number from 1 - 10!");

        int myNum = SCANNER.nextInt();

        return myNum;
    }

    public static void SimpleMethod() {
        Print("HELLO WORLD!");
    }

    public static void Print(Object obj) {
        System.out.println(obj);
    }
}
