/*
 * This source file was generated by the Gradle 'init' task
 */
package app;

import java.io.*;
import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int sum = 0;
        
        try (InputStream inStream = App.class.getResourceAsStream("/input")) {
            int current;
            int firstChar = -1;
            int lastChar = -1;

            while((current = inStream.read()) != -1) {
                char currentChar = (char) current;

                if (currentChar == '\n') {
                    if(firstChar != -1 && lastChar != -1) {
                        sum += Integer.parseInt(String.valueOf((char)firstChar) + (char)lastChar);
                        String numStr = String.valueOf((char)firstChar) + (char)lastChar;

                        System.out.println("EOL:\t" + numStr);

                        firstChar = -1;
                        lastChar = -1;
                        continue;
                    } else if (firstChar != -1 ) {
                        String numStr = String.valueOf((char) firstChar) + (char) firstChar;
                        sum += Integer.parseInt(numStr);

                        System.out.println("EOL:\t" + numStr);

                        firstChar = -1;
                        continue;
                    }
                }

                if(currentChar < 49 || currentChar > 57) continue;

                if(firstChar == -1) {
                    firstChar = currentChar;
                    System.out.println("First Num:\t" + (char) firstChar);
                } else {
                    lastChar = currentChar;
                    System.out.println("First Num:\t" + (char) firstChar + "\tLast Num:\t" + (char) lastChar);
                }
            }
        } 
        catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println(Arrays.toString(e.getStackTrace()));
        }

        System.out.println(sum);

    }
}
