/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

application {
    // Define the main class for the application.
    mainClass = "app.App"
}

sourceSets {
    main {
        java.srcDirs("app")
        resources.srcDirs("app/resources")
    }
    
    test {
        java.srcDirs("test")
        resources.srcDirs("test/resources")
    }
}
