/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package primitives;

public class App {
    public static void main(String[] args) {
        int age;

        age = 25;

        char c = 97;

        Print(c);

        Exercises.main(new String[]{"hello"});
    }

    public static void Print(Object message) {
        System.out.println(message);
    }
}
